### ISSUE TITLE
how can i use this on Desktop APP

### ISSUE THREAD

**Issue by passage2011** [BoardiesITSolutions/SSH-Tunnel-Plugin#3]
how can i use this on Desktop APP(console or exe)
like naticat client

**Comment by boardy** [comment]
Hi, 

This isn't a MySQL client, this is a plugin to the [PHP API](https://github.com/BoardiesITSolutions/Boardies-MySQL-Manager-PHP-API) which controls our Android app [Boardies MySQL Manager](https://play.google.com/store/apps/details?id=com.BoardiesITSolutions.MysqlManager) which is a lightweight MySQL client but only runs on devices running Android. Unfortunately doesn't support desktop applications. 

Hope this help but if you have any other questions, then please let me know.

**Comment by passage2011** [comment]
I've just compiled it with VS2013, but I don't know how to connect mysql like naticat, and I'll try  it again.thanks

**Comment by boardy** [comment]
Hi, 

You won't be able to use the SSH-Tunnel-Plugin to use with naticat, it will only work with our android app and PHP API. 

I don't know much about naticat but it looks like they do SSH tunnelling built in. Maybe https://www.namecheap.com/support/knowledgebase/article.aspx/9329/2180/how-to-connect-to-database-using-navicat-mysql-client this will help.
